In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("OLA_Bookings_100000_Raws_Data.xlsx")
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [3]:
print("Shape:", df.shape)

Shape: (103024, 20)

In [4]:
print(df.columns)

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle Images'],
      dtype='str')

In [5]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 15.7+ MB
None

In [6]:
df.describe()

,Date,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,103024,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000
mean,2024-07-16 11:31:38.879678,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313
min,2024-07-01 00:00:00,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,2024-07-08 18:41:00,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,2024-07-16 11:23:00,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000
75%,2024-07-24 05:18:00,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000
max,2024-07-31 23:58:00,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000
std,NaN,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957

In [7]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [8]:
print("\nDuplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [9]:
df = df.drop_duplicates()

In [10]:
# drop for unwanted data
df = df.drop(columns=["Vehicle Images",'Incomplete_Rides_Reason'])

In [11]:
print("Remaining duplicates:", df.duplicated().sum())

Remaining duplicates: 0

In [12]:
missing_percent = df.isnull().sum() / len(df) * 100
missing_percent.sort_values(ascending=False)

Canceled_Rides_by_Customer    89.809171
Canceled_Rides_by_Driver      82.107082
Payment_Method                37.910584
Incomplete_Rides              37.910584
V_TAT                         37.910584
C_TAT                         37.910584
Driver_Ratings                37.910584
Customer_Rating               37.910584
Time                           0.000000
Date                           0.000000
Pickup_Location                0.000000
Drop_Location                  0.000000
Customer_ID                    0.000000
Vehicle_Type                   0.000000
Booking_Status                 0.000000
Booking_ID                     0.000000
Booking_Value                  0.000000
Ride_Distance                  0.000000
dtype: float64

In [13]:
#  Missing handle values 

# numeric aur categorical seprate 
num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object','str']).columns
print(num_cols)
print(cat_cols)

Index(['V_TAT', 'C_TAT', 'Booking_Value', 'Ride_Distance', 'Driver_Ratings',
       'Customer_Rating'],
      dtype='str')
Index(['Time', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type',
       'Pickup_Location', 'Drop_Location', 'Canceled_Rides_by_Customer',
       'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Payment_Method'],
      dtype='str')

In [14]:
for col in num_cols:
    percent = df[col].isnull().mean()*100
    
    if percent > 50:
        df=df.drop(columns=col)
        print(col, "drop (>50% missing)")
    
    elif percent > 0:
        df[col]=df[col].fillna(df[col].median())

In [15]:
for col in cat_cols:
    percent = df[col].isnull().mean()*100
    
    if percent > 100:
        df.drop(columns=col)
        print(col, "droped")
    
    elif percent > 0:
        df[col]=df[col].fillna(df[col].mode()[0])
        print(col, "mode se fill kiya")

Canceled_Rides_by_Customer mode se fill kiya
Canceled_Rides_by_Driver mode se fill kiya
Incomplete_Rides mode se fill kiya
Payment_Method mode se fill kiya

In [16]:
df.isna().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64

In [17]:
# print(df['Canceled_Rides_by_Customer'].unique(),"\n")
# print(df['Canceled_Rides_by_Driver'].unique(),"\n")
# print(df['Incomplete_Rides'].unique(),"\n")
# print(df['Payment_Method'].unique())

In [18]:
df['Time'].head(10)

0    14:00:00
1    22:20:00
2    19:59:00
3    03:15:00
4    09:02:00
5    04:42:00
6    09:51:00
7    11:12:00
8    19:19:00
9    01:31:00
Name: Time, dtype: object

In [19]:
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce')

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  datetime64[us]
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            103024 non-null  str
 13  Booking_Value               103024 non-null  int64
 14  Payment_Method              103024 non-null  str
 15  Ride_Distance               103024 non-null  int64
 16  Driver_Ratings              103024 non-null  float64
 17  Customer_Rating             103024 non-null  float64
dtypes: datetime64[us](2), float64(4), int64(2), str(10)
memory usage: 14.1 MB

In [21]:
df.to_csv("cleaned_data.csv")